#ifndef LEXEME_H_
#define LEXEME_H_
enum lexemeType{NAME,INT_CONST,FLOAT_CONST,NEG,PLUS,MINUS,MULT,DIV,ASSIGNMENT,OPPNUMBER,EQUAL,MORE,
			LESS,AND,OR,DUP,DROP,SWAP,PUT,ROT,IF,WHILE,CALL,CHANGE,SEND,FUNC_OPEN,FUNC_CLOSE,
			ARRAY_OPEN,ARRAY_CLOSE,ERROR,STMT};
struct lexeme
{
	lexemeType type;
	int value;
};
#endif
